TruYum_WebApp/Models/Cart.cs
namespace TruYum_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Cart")]
    public partial class Cart
    {
        [Key]
        public int Id { get; set; }
        public int MenuItemId { get; set; }

        public int Quantity { get; set; }

        public int? UserId { get; set; }

        public virtual MenuItem MenuItem { get; set; }

        public virtual User User { get; set; }
    }
}

TruYum_WebApp/Controllers/CartController.cs
using TruYum_WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TruYumWeb.Controllers
{
    public class CartController : Controller
    {
        int userId = 2;
        public decimal total = 0;

        TruYumContext cdx = new TruYumContext();
        public ActionResult Index()
        {
            try
            {
                total = 0;
                List<MenuItem> lstResult = new List<MenuItem>();
                List<Cart> lstCarts = cdx.Carts.Where(e => e.UserId == userId).ToList();
                List<MenuItem> lstMenuItems = cdx.MenuItems.Where(e => e.Active == true&& e.dateOfLaunch<DateTime.Now).ToList();
                if (lstCarts != null && lstCarts.Count > 0 && lstMenuItems != null && lstMenuItems.Count > 0)
                {
                    MenuItem obj = null;
                    foreach (Cart cart in lstCarts)
                    {
                        obj = lstMenuItems.Where(e => e.Id == cart.MenuItemId).SingleOrDefault();
                        if (obj != null)
                        {
                            total = total + obj.price;
                            lstResult.Add(obj);
                        }
                    }


                    var list = lstResult;
                    ViewData["total"] = total;
                    return View(list);
                }
                else
                {
                    return View("Empty");
                }
            }
            catch (Exception e)
            {
                return View("Error", (object)e.Message.ToString());
            }
        }


        public ActionResult Delete(int id)

        {
            try
            {
                List<Cart> cart = cdx.Carts.Where(e => e.UserId == userId && e.MenuItemId == id).ToList();
                foreach (var x in cart)
                {
                    if (cart != null)
                    {
                        cdx.Carts.Remove(x);
                        cdx.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error", (object)e.Message.ToString());
            }
        }


    }
}

TruYum_WebApp/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TruYum_WebApp.Models;
namespace TruYumWeb.Controllers
{
    public class MenuItemController : Controller
    {

        TruYumContext cdx = new TruYumContext();
        public ActionResult Index()
        {
            var list = cdx.MenuItems.Where(e => e.Active == true&&e.dateOfLaunch<DateTime.Now).ToList();
            return View(list);
        }

        public ActionResult AddToCart(int id)
        {
            try
            {

                int userId = 2;
                Cart cart = new Cart();
                cart.UserId = userId;
                cart.MenuItemId = id;
                cart.Quantity = 1;
                cdx.Carts.Add(cart);
                cdx.SaveChanges();
                return RedirectToAction("Index", "Cart");

            }
            catch (Exception e)
            {
                return View("Error", (object)e.Message.ToString());
            }
        }



    }







}

TruYum_WebApp/Views/Cart/Empty.cshtml
@{
    ViewBag.Title = "Empty";
}

<h2>View Cart</h2>
No items in cart. @Html.ActionLink("View Menu Items", "Index", "MenuItem")

TruYum_WebApp/Views/Cart/Index.cshtml
@model IEnumerable<TruYum_WebApp.Models.MenuItem>

@{
    ViewBag.Title = "My Cart";
}

<h2>View Cart</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayName("Free Delivery")
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>


        <th>
            @Html.DisplayName("Action")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>
                Rs.@Html.DisplayFor(modelItem => item.freeDelivery)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>

            <td>
                @Html.ActionLink("Remove", "Delete", new { id = item.Id })

            </td>
        </tr>
    }
    <tr>
        <td><b>Total: </b></td>
        <td colspan="100%">
            Rs.@ViewData["total"].ToString()
        </td>
    </tr>
</table>

<div>
    @Html.ActionLink("View Menu Items", "Index", "MenuItem")
</div>